export const GET_COMPANIES = 'GET_COMPANIES';
export const LOAD_COMPANIES = 'LOAD_COMPANIES';
export const SET_COMPANIES = 'LOAD_COMPANIES';

// FORM ACTION
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
